### ISSUE TITLE
Nullable option

### ISSUE THREAD

**Issue by CleitonDeLima** [lagden/currency#1]
Hi @lagden 

Cool what you did here! 
Enable the option to leave a null value in the input, how?

**Comment by lagden** [comment]
Olá @CleitonDeLima 

O `input` é um **DOMString.**
https://developer.mozilla.org/en-US/docs/Web/API/DOMString

> Certain Web APIs accepting a DOMString have an additional legacy behavior, where passing null stringifies to the empty string instead of the usual "null".

Nesse caso você terá que ajustar seu backend.
Em vez de `null` passar `""`.

**Comment by CleitonDeLima** [comment]
> Olá @CleitonDeLima
> 
> O `input` é um **DOMString.**
> https://developer.mozilla.org/en-US/docs/Web/API/DOMString
> 
> > Certain Web APIs accepting a DOMString have an additional legacy behavior, where passing null stringifies to the empty string instead of the usual "null".
> 
> Nesse caso você terá que ajustar seu backend.
> Em vez de `null` passar `""`.

Correto, quis dizer na questão da mask, se eu escrever algum valor e quiser deixar o campo vazio novamente (com `""`), lá no backend o valor seria `null`.
Seria legal uma opção assim. Gostei bastante da mask mas não achei nada que me ajude nessa questão de valores vazios.

**Comment by lagden** [comment]
Claro!

Uma vez que digitou, já fica `0,00`, por exemplo.
Vou analisar e te dou um retorno.

**Comment by lagden** [comment]
O exemplo está lá no codepen:
https://codepen.io/lagden/pen/jOrZVjg?editors=1010

No `enter amount`

**Comment by CleitonDeLima** [comment]
@lagden com empty não consigo informar valores com zeros: `0.00`

**Comment by lagden** [comment]
hehehe...

o `empty` ainda existe, mas prefira o `backspace` no seu caso.
tá na documentação e no codepen!!

**Comment by lagden** [comment]
P.S. A lib foi feita com propósito de trabalhar com declarações reativas.
Exemplo: https://svelte.dev/repl/23aa961ec2b14e3592b43dfa72369712?version=3.38.2
