### ISSUE TITLE
The Intl.NumberFormat options not working

### ISSUE THREAD

**Issue by mccarlosen** [lagden/currency#2]
Hi! I am using this library. But I have a question.

How can I change the decimal separator from `,` to `.`?

Example: from `1.234,56` to `1234.56`.

```js
new Currency(this.element, {
    maskOpts: {
        locales: "es-ES",
	options: {
            decimal: "."
        }
    }
})
```

**Comment by lagden** [comment]
Hi!

```js
const maskOpts = {
  locales: 'en-US',
  options: {
    useGrouping: false,
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  },
}

// static
Currency.masking('1.234,56', maskOpts) // => 1234.56

// instance
new Currency(input, {maskOpts})
```


You can see here for more options:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#syntax
