### ISSUE TITLE
Ideas to make currency dynamic

### ISSUE THREAD

**Issue by JonatasAmaral** [lagden/currency#3]
Following the [mask](https://github.com/lagden/mask)'s repo [PR discussion](https://github.com/lagden/mask/pull/9#issuecomment-1573794677), i'm dropping here the ideas to make this currency dynamic, so you can keep track of it, if does make sense for this.

### [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver)
This could be considered to add dynamics here, if like on the [mask](https://github.com/lagden/mask) lib, configs could be placed in data-attributes of the input. 

### [Setter/Getter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get)
As i could test now, if dynamic changing the instances' `opts.MaskOpts`, the input will change it's mask, but only after a new type event.
If you can transform that `opts.maskOpts` into a setter, you could than attach a logic to immediately update the input when it changes (and merge current options with existing ones, making it stronger and error proof. e.g. prevent wrong locale format)

This one honestly seen as better fit to this lib here

**Comment by lagden** [comment]
This library is a little bit different than [lagden/mask](https://github.com/lagden/mask).
Send a PR if you wish! I will look with attention and care.
