### ISSUE TITLE
Masking of values for currency ISK and JPY always results in `0`

### ISSUE THREAD

**Issue by matthiasschaub** [lagden/currency#9]
Reproducible by changing the currency of the [CodePen](https://codepen.io/lagden/pen/jOrZVjg?editors=1010) example to `ISK` and trying out the input field.

```javascript
new Currency(input, {
	maskOpts: {
		empty: true,
		locales: 'de-DE',
		options: {
			style: 'currency',
			currency: 'ISK'
		}
	}
})
```

After setting currency to ISK, no matter what number are typed in the input field always show `0`.
 
![image](https://github.com/lagden/currency/assets/83658582/857ee27e-2059-4cc6-895d-9dda85b34271)

I love this little gem of yours. It's exactly what I need and so small :) 
Thanks for creating and sharing `currency`. I hope this can be fixed at some point. I am not proficient in JavaScript otherwise I would have dug into the code myself and find out the problem.

**Comment by lagden** [comment]
Hi @matthiasschaub 

I fixed and added the `ISK` and `JPY` currency on codepen.
Enjoy and confirm if is correctly.

https://codepen.io/lagden/pen/jOrZVjg

**Comment by matthiasschaub** [comment]
Awesome. I can confirm that it works now! Thank you.
